careforall/careforall/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from careforallapp import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.base, name='base'),
    url(r'^datasecurity/',  include("datasecurity.urls", namespace="datasecurity")),
    url(r'^fitness/',  include("fitness.urls", namespace="fitness")),
    url(r'^personality/',  include("personality.urls", namespace="personality")),
    


]

careforall/careforallapp/urls.py
from django.conf.urls import url


#URLs

careforall/datasecurity/urls.py
from django.conf.urls import url

from . import views

app_name = 'datasecurity'

urlpatterns = [
    url(r'^$', views.datasecurity, name="datasecurity"),
    url(r'^datasecurity/(?P<slug>[^/]+)', views.blogHome, name='blogHome')
]

careforall/fitness/urls.py
from django.conf.urls import url

from . import views

app_name = 'fitness'

urlpatterns = [
    url(r'^$', views.fitness, name="fitness"),
    url(r'^fitness/(?P<slug>[^/]+)', views.blogfit, name='blogfit')
]

careforall/personality/urls.py
from django.conf.urls import url

from . import views

app_name = 'personality'

urlpatterns = [
    url(r'^$', views.personality, name="personality"),
    url(r'^personality/(?P<slug>[^/]+)', views.blogpersonal, name='blogpersonal')
]

careforall/careforallapp/models.py
from django.db import models
from ckeditor.fields import RichTextField

careforall/datasecurity/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Post(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=14)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(blank=True)
    content=RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title + " by " + self.author

careforall/fitness/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Post(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=14)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(blank=True)
    content=RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title + " by " + self.author

careforall/personality/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Post(models.Model):
    sno=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=14)
    slug=models.CharField(max_length=130)
    timeStamp=models.DateTimeField(blank=True)
    content=RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title + " by " + self.author

careforall/careforallapp/forms.py
from django import forms
from django.contrib.auth.models import User
from careforallapp.models import UserProfileInfo

#LANGUAGE_CODE
class UserForm(forms.ModelForm):
    password = forms.CharField(widget= forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

careforall/careforallapp/views.py
from django.shortcuts import render


# Create your views here.

def base(request):
    return render(request,'careforallapp/base.html')

careforall/datasecurity/views.py
from django.shortcuts import render
from datasecurity.models import Post

# Create your views here.
def datasecurity(request):
    allPosts= Post.objects.all()
    context={'allPosts': allPosts}
    return render(request, 'datasecurity/data.html',context=context)

def blogHome(request, slug):
    post=Post.objects.filter(slug=slug).first()
    context={"post":post}
    return render(request, "datasecurity/blogHome.html", context)

careforall/fitness/views.py
from django.shortcuts import render
from fitness.models import Post
# Create your views here.
def fitness(request):
    everypost=Post.objects.all()
    context={"everypost":everypost}
    return render(request, "fitness/fit.html", context)


def blogfit(request, slug):
    post=Post.objects.filter(slug=slug).first()
    context={"post":post}
    return render(request, "fitness/blogfit.html", context)

careforall/personality/views.py
from django.shortcuts import render
from personality.models import Post
# Create your views here.
def personality(request):
    ppost=Post.objects.all()
    context={"ppost":ppost}
    return render(request, "personality/personal.html", context)

def blogpersonal(request, slug):
    post=Post.objects.filter(slug=slug).first()
    context={"post":post}
    return render(request, "personality/blogpersonal.html", context)

careforall/careforallapp/templates/careforallapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/firstpage.css' %}">
  <title>My Website</title>
</head>
<body>
  <!-- Header -->
  <section id="header">
    <div class="header container">
      <div class="nav-bar">
        <div class="brand" >
          <a href="#hero" id = "main"><img src = "{% static 'css/lasso4.png' %}" class= "logo"></a>
          <a href="#hero"><h1><span>C</span>are for <span>A</span>LL</h1></a>
        </div>
        <div class="nav-list">
          <div class="hamburger"><div class="bar"></div></div>
          <ul>
            <li><a href="#hero" data-after="Home">Home</a></li>
            <li><a href="#services" data-after="Service">Services</a></li>
            <li><a href="#projects" data-after="Projects">Projects</a></li>
            <li><a href="#about" data-after="About">About</a></li>
            <li><a href="#contact" data-after="Contact">Contact</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- End Header -->


  <!-- Hero Section  -->
  <section id="hero">
    <div class="hero container">
      <div>
        <h1>Happy <span></span></h1>
        <h1>New Year, <span></span></h1>
        <h1>2021<span></span></h1>
        <p>All Human Beings Are Superior Than Me Because I Believe Each One Of Them Is Good At Something Which I Am Not.To Get The Things That You Don't Have Now Is Only Possible Only You Become Someone You Are Not Today<span></span></p>

      </div>
    </div>
  </section>
  <!-- End Hero Section  -->

  <!-- Service Section -->
  <section id="services">
    <div class="services container">
      <div class="service-top">
        <h1 class="section-title">Serv<span>i</span>ces</h1>
        <p>We don't want to push our ideas on to readers, we simply want to make what they want.</p>
      </div>
      <div class="service-bottom">
        <div class="service-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png"/></div>
          <h2>Trusted Knowledge</h2>
          <p>We provide you the valid and trusted data. We dont provide fake data</p>
        </div>
        <div class="service-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png"/></div>
          <h2>Safe Website</h2>
          <p>You are in safe environment, we use all type of hashing and layers to protect our websites.</p>
        </div>
        <div class="service-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png"/></div>
          <h2>3 Best Topics</h2>
          <p>We give you the 3 best topics. You can visit anyone of them. They are all hot topics.</p>
        </div>
        <div class="service-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png"/></div>
          <h2>Contact Us Anytime</h2>
          <p>Contact us for any queries related to these topic. We are excited to solve your queries.  </p>
        </div>
      </div>
    </div>
  </section>
  <!-- End Service Section -->

  <!-- Projects Section -->
  <section id="projects">
    <div class="projects container">
      <div class="projects-header">
        <h1 class="section-title">TOPICS <span>To COVER</span></h1>
      </div>
      <div class="all-projects">
        <div class="project-item">
          <div class="project-info">
            <a href="{% url 'datasecurity:datasecurity' %}" style="color: #8ebf42"><h1>Data Security</h1></a>
            <h2>Data Is The Modern Fuel</h2>
            <p>Digital technology is changing the way in which society is operating and the ways we live our lives. Every day, there is new ways to work and to play, new methods of interacting with one another. As our digital footprint grows exponentially, we are forming our own online identities.</p>
          </div>
          <div class="project-img">
            <img src="{% static 'css/ds.jpg' %}" alt="img">
          </div>
        </div>
        <div class="project-item">
          <div class="project-info">
            <a href="{% url 'fitness:fitness' %}" style="color: #8ebf42"><h1>Health and Fitness</h1></a>
            <h2>The Science Behind A Good Workout</h2>
            <p>We’ve all been there before: a tough day at work or in school. We’re exhausted, both mentally and physically, but we still manage to push ourselves and get to the gym. Why do we do it? Because we know how much better we’ll feel after an evening indoor cycling class, an hour of football or a challenging weight workout. We leave feeling refreshed, rejuvenated and invigorated—truly transformed. Clearly, there’s a relationship between exercise and the brain, but what is it?</p>
          </div>
          <div class="project-img">
            <img src="{% static 'css/fit-3.jpg' %}" alt="img">
          </div>
        </div>
        <div class="project-item">
          <div class="project-info">
            <a href="{% url 'personality:personality' %}" style="color: #8ebf42"><h1>Personality Development</h1></a>
            <h2>THE IMPORTANCE OF GOAL SETTING </h2>
            <p>We know the importance of goal setting, but most times our goals are not measurable and clearly defined. You hear people say things like “I want to lose weight”, though losing weight is a goal it can be clearly defined if you add things like: “I want to lose weight, by eating healthy and exercising. When you compare both statements, the first one only states what you intend to do, the second one states what you intend to do and how you intend to do it. </p>
          </div>
          <div class="project-img">
            <img src="{% static 'css/tt.jpg' %}" alt="img">
          </div>
        </div>
    </div>
  </section>
  <!-- End Projects Section -->

  <!-- About Section -->
  <section id="about">
    <div class="about container">
      <div class="col-left">
        <div class="about-img">
          <img src="{% static 'css/hit.jpeg' %}" alt="img">
        </div>
      </div>
      <div class="col-right">
        <h1 class="section-title">Mr.<span>Hitesh Kumar</span></h1>
        <h2>Designer and Editor</h2>
        <p>Qualification: Pursuing PGDM from Indus Business Academy, Banglore</p>
      </div>
    </div>
  </section>
  <section id="about">
    <div class="about container">
      <div class="col-left">
        <div class="about-img">
          <img src="{% static 'css/ash-2.jpeg' %}" alt="img">
        </div>
      </div>
      <div class="col-right">
        <h1 class="section-title">Mr.<span>Ashwini Kumar</span></h1>
        <h2>Content Writer</h2>
        <p>Qualification: Pursuing B.Tech From MVIT, Banglore</p>
      </div>
    </div>
  </section>
  <section id="about">
    <div class="about container">
      <div class="col-left">
        <div class="about-img">
          <img src="{% static 'css/asu.jpeg' %}" alt="img">
        </div>
      </div>
      <div class="col-right">
        <h1 class="section-title">Mr.<span>Asutosh</span></h1>
        <h2>Content Writer</h2>
        <p>Qualification: Pursuing B.A From Hislop College, Nagpur</p>
      </div>
    </div>
    <section id="about">
      <div class="about container">
        <div class="col-left">
          <div class="about-img">
            <img src="{% static 'css/hri.jpeg' %}" alt="img">
          </div>
        </div>
        <div class="col-right">
          <h1 class="section-title">Mr.<span>Hrithik Singh</span></h1>
          <h2>Web Developer</h2>
          <p>Qualification: _</p>
        </div>
      </div>
      <section id="about">
        <div class="about container">
          <div class="col-left">
            <div class="about-img">
              <img src="{% static 'css/nam.jpg' %}" alt="img">
            </div>
          </div>
          <div class="col-right">
            <h1 class="section-title">Mr.<span>Naman Rohilla</span></h1>
            <h2>Web Developer</h2>
            <p>Qualification: Pursuing Integrated Course in M.Sc Mathematics from SVNIT, Surat</p>
          </div>
        </div>

  </section>
  <!-- End About Section -->

  <!-- Contact Section -->
  <section id="contact">
    <div class="contact container">
      <div><h1 class="section-title">Contact <span>info</span></h1></div>
      <div class="contact-items">
        <div class="contact-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/new-post.png"/></div>
          <div class="contact-info">
            <h1>Email</h1>
            <h2>careall249@gmail.com</h2>
          </div>
        </div>
        <div class="contact-item">
          <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/map-marker.png"/></div>
          <div class="contact-info">
            <h1>Address</h1>
            <h2>MVIT, Banglore</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Contact Section -->

  <!-- Footer -->
  <section id="footer">
    <div class="footer container">
      <div class="brand"><h1><span>C</span>are For <span>A</span>ll</h1></div>
      <h2>Your Complete Web Solution</h2>
      <div class="social-icon">

        <div class="social-item">
          <a href="https://www.instagram.com/_care4all_/?igshid=r0bnwlhb8cbm"><img src="https://img.icons8.com/bubbles/100/000000/instagram-new.png"/></a>
        </div>
        <div class="social-item">
          <a href="https://twitter.com/CareForAll249?s=08"><img src="https://img.icons8.com/bubbles/100/000000/twitter.png"/></a>
        </div>
        <div class="social-item">
          <a href="https://www.facebook.com/Care-For-All-101858671850233/"><img src="https://img.icons8.com/bubbles/100/000000/facebook-new.png"/></a>
        </div>

      </div>
      <p>Copyright © 2020 Arfan. All rights reserved</p>
    </div>
  </section>
  <!-- End Footer -->
  <script src="{% static 'css/firstpage.js' %}"></script>
</body>
</html>

careforall/datasecurity/templates/datasecurity/blogHome.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/datasecurity.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="noEcH88O"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
  </head>
  <body>

  <div class="jumbotron">
    <div class="container my-3">
     <div class="blog-post">
        <h2 class="blog-post-title">{{post.title}}</h2>
        <p class="blog-post-meta">{{post.timeStamp}} by <a href="#">{{post.author}}</a></p>

        <p>{{post.content|safe}}</p>
        <div class="fb-like" data-href="http://127.0.0.1:8000/datasecurity/datasecurity/{{post.post_id}}" data-layout="standard" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div><br>
        <div class="fb-comments" data-href="http://127.0.0.1:8000/datasecurity/datasecurity/{{post.post_id}}" data-width="" data-numposts="5"></div>
        <hr>
      </div>
      </div>
   </div>
  </body>
</html>

careforall/datasecurity/templates/datasecurity/data.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/datasecurity.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="noEcH88O"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>

  </head>
  <body>

   <section id = 'main'>
    <div class="jumbotron">
    <div class="container my-3">
    <h2>Data Security</h2>
    {% for post in allPosts  %}
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="card-body">
            <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
            <h4 class="mb-0">{{post.title}}</h3>

            <h3 class="card-text">{{post.content|safe | truncatechars:300}}</h3>
            <h2 class="mb-0">{{post.datetime}}</h4>
            <div class="my-2">
                <a href="{% url 'datasecurity:blogHome' slug=post.slug %}" role="button" class="btn btn-primary">Continue reading</a>
            </div>
            
        </div>

        </div>

        {% endfor %}
    </div>
    <div>
    </section>
  </div>
  </body>
</html>

careforall/fitness/templates/fitness/blogfit.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/fitness.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="noEcH88O"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
  </head>
  <body>

  <div class="jumbotron">
    <div class="container my-3">
     <div class="blog-post">
        <h2 class="blog-post-title">{{post.title}}</h2>
        <p class="blog-post-meta">{{post.timeStamp}} by <a href="#">{{post.author}}</a></p>

        <p>{{post.content|safe}}</p>
        <div class="fb-like" data-href="http://127.0.0.1:8000/fitness/fitness/{{post.post_id}}" data-layout="standard" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div><br>
        <div class="fb-comments" data-href="http://127.0.0.1:8000/fitness/fitness/{{post.post_id}}" data-width="" data-numposts="5"></div>
        <hr>
      </div>
      </div>
   </div>
  </body>
</html>

careforall/fitness/templates/fitness/fit.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/fitness.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="noEcH88O"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
    </style>
  </head>
  <body>

    <div class="jumbotron">
    <div class="container my-3">
    <h2>Health and Fitness</h2>
    {% for post in everypost  %}
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="card-body">
            <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
            <h3 class="mb-0">{{post.title}}</h3>

            <p class="card-text">{{post.content|safe  | truncatechars:300}}</p>
            <h4 class="mb-0">{{post.datetime}}</h4>
            <div class="my-2">
                <a href="{% url 'fitness:blogfit' slug=post.slug %}" role="button" class="btn btn-primary">Continue reading</a>
            </div>


        </div>

        </div>

        {% endfor %}
    </div>
    <div>

  </div>
  </body>
</html>

careforall/personality/templates/personality/blogpersonal.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/personality.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="noEcH88O"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
  </head>
  <body>

  <div class="jumbotron">
    <div class="container my-3">
     <div class="blog-post">
        <h2 class="blog-post-title">{{post.title}}</h2>
        <p class="blog-post-meta">{{post.timeStamp}} by <a href="#">{{post.author}}</a></p>

        <p>{{post.content|safe}}</p>
        <div class="fb-like" data-href="http://127.0.0.1:8000/personality/personality/{{post.post_id}}" data-layout="standard" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div><br>
        <div class="fb-comments" data-href="http://127.0.0.1:8000/personality/personality/{{post.post_id}}" data-width="" data-numposts="5"></div>
        <hr>
      </div>
      </div>
   </div>
  </body>
</html>

careforall/personality/templates/personality/personal.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/personality.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" nonce="noEcH88O"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
    </style>
  </head>
  <body>

    <div class="jumbotron">
    <div class="container my-3">
    <h2>Personality Development</h2>
    {% for post in ppost  %}
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="card-body">
            <strong class="d-inline-block mb-2 text-primary">Article  by {{post.author}}</strong>
            <h3 class="mb-0">{{post.title}}</h3>

            <p class="card-text">{{post.content|safe | truncatechars:100}}</p>
            <h4 class="mb-0">{{post.datetime}}</h4>
            <div class="my-2">
                <a href="{% url 'personality:blogpersonal' slug=post.slug %}" role="button" class="btn btn-primary">Continue reading</a>
            </div>

            <div class="fb-like" data-href="http://127.0.0.1:8000/personality/personality/{{post.post_id}}" data-layout="standard" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div><br>
            <div class="fb-comments" data-href="http://127.0.0.1:8000/personality/personality/{{post.post_id}}" data-width="" data-numposts="5"></div>


        </div>

        </div>

        {% endfor %}
    </div>
    <div>

  </div>
  </body>
</html>